export const TIBIA_CONSTANTS = {
  GAME_ID: 'tibia',
  GAME_NAME: 'Tibia MMORPG',
  CURRENCY_MULTIPLIER: 25,
  BASE_PACKAGE_SIZE: 250,
  MIN_TRANSACTION_AMOUNT: 25,
  MAX_TRANSACTION_AMOUNT: 1000000,
  ALLOWED_CURRENCIES: ['TC', 'USD', 'EUR'] as string[],
  ITEM_CODES: {
    TIBIA_COINS: 'TC',
    RECOVERY_KEY: 'RK'
  }
} as const; 